In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("tvsubscriptions.csv")
df.head()

,user_id,device_type,genre_primary,title,watch_duration_minutes,progress_percentage,watch_date
0,user_07271,Tablet,Music,Dragon Princess,63.9,34.6,2025-11-13
1,user_01686,Smart TV,Animation,Secret Battle,50.4,62.1,2025-05-17
2,user_00770,Desktop,Western,A King,34.7,69.7,2025-08-09
3,user_05312,Tablet,Western,Night Journey,59.9,30.7,2025-10-17
4,user_05052,Laptop,Western,Big Story,31.0,65.2,2024-12-09

In [3]:
nbr_genres = df['genre_primary'].nunique()
print(nbr_genres)

20

In [4]:
top_3_films = df['title'].value_counts().head(3)
print(top_3_films)

title
A Adventure    83
Dream Dream    68
A Quest        68
Name: count, dtype: int64

In [5]:
average_duration = df['watch_duration_minutes'].mean()
print(average_duration)

63.69193428722842

In [6]:
completed_sessions = df[df['progress_percentage'] == 100].shape[0]
print(completed_sessions)

3

In [7]:
df['watch_month'] = pd.to_datetime(df['watch_date']).dt.month
df["watch_month"]

0       11.0
1        5.0
2        8.0
3       10.0
4       12.0
        ...
9431     7.0
9432     8.0
9433     5.0
9434     5.0
9435     NaN
Name: watch_month, Length: 9436, dtype: float64

In [8]:
df.iloc[0:5]

,user_id,device_type,genre_primary,title,watch_duration_minutes,progress_percentage,watch_date,watch_month
0,user_07271,Tablet,Music,Dragon Princess,63.9,34.6,2025-11-13,11.0
1,user_01686,Smart TV,Animation,Secret Battle,50.4,62.1,2025-05-17,5.0
2,user_00770,Desktop,Western,A King,34.7,69.7,2025-08-09,8.0
3,user_05312,Tablet,Western,Night Journey,59.9,30.7,2025-10-17,10.0
4,user_05052,Laptop,Western,Big Story,31.0,65.2,2024-12-09,12.0

In [9]:
df.iloc[0 , 2]

'Music'

In [10]:
df.loc[0]

user_id                        user_07271
device_type                        Tablet
genre_primary                       Music
title                     Dragon Princess
watch_duration_minutes               63.9
progress_percentage                  34.6
watch_date                     2025-11-13
watch_month                          11.0
Name: 0, dtype: object

In [11]:
df[df.genre_primary == "Music"]

,user_id,device_type,genre_primary,title,watch_duration_minutes,progress_percentage,watch_date,watch_month
0,user_07271,Tablet,Music,Dragon Princess,63.9,34.6,2025-11-13,11.0
16,user_08839,Mobile,Music,Story Journey,13.3,46.5,2025-03-21,3.0
44,user_08111,Mobile,Music,Journey Fire,18.3,96.8,2025-08-06,8.0
53,user_04637,Laptop,Music,Our Mission,51.7,37.0,2025-04-18,4.0
68,user_06586,Mobile,Music,Dragon Quest,7.8,1.3,2024-05-31,5.0
...,...,...,...,...,...,...,...,...
9338,user_04367,Laptop,Music,Phoenix Ice,25.5,50.0,2024-07-06,7.0
9342,user_07796,Tablet,Music,Adventure Love,86.4,93.8,2025-04-01,4.0
9422,user_04339,Laptop,Music,King Day,110.7,66.5,2024-02-13,2.0
9425,user_05177,Laptop,Music,Dragon Princess,76.7,77.8,2024-06-06,6.0
9429,user_07122,Desktop,Music,Last Phoenix,51.7,34.5,2025-08-09,8.0

In [12]:
df.groupby('device_type')['genre_primary'].size()

device_type
Desktop     1897
Laptop      1874
Mobile      1878
Smart TV    1930
Tablet      1856
Name: genre_primary, dtype: int64

In [13]:
df.device_type.unique()
df.genre_primary.value_counts()

genre_primary
History        630
War            578
Family         563
Documentary    553
Western        547
Adventure      539
Sci-Fi         514
Action         512
Comedy         487
Drama          469
Animation      468
Romance        462
Biography      460
Crime          431
Music          409
Sport          390
Fantasy        383
Thriller       371
Horror         342
Mystery        327
Name: count, dtype: int64

In [14]:
df.isnull()

,user_id,device_type,genre_primary,title,watch_duration_minutes,progress_percentage,watch_date,watch_month
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
9431,False,False,False,False,False,False,False,False
9432,False,False,False,False,False,False,False,False
9433,False,False,False,False,False,False,False,False
9434,False,False,False,False,False,False,False,False
9435,False,True,True,True,True,True,True,True

In [16]:
df.sort_values('genre_primary' , ascending=False)

,user_id,device_type,genre_primary,title,watch_duration_minutes,progress_percentage,watch_date,watch_month
6424,user_04146,Tablet,Western,Journey Mystery,101.2,51.6,2025-06-30,6.0
1384,user_03421,Tablet,Western,Dragon Day,63.1,9.0,2025-10-16,10.0
7009,user_07838,Smart TV,Western,The Empire,21.8,45.2,2025-03-10,3.0
1395,user_01089,Smart TV,Western,House House,35.3,8.7,2025-06-20,6.0
6994,user_07976,Desktop,Western,Day Dream,69.2,57.9,2024-05-19,5.0
...,...,...,...,...,...,...,...,...
4962,user_07796,Mobile,Action,Story Queen,132.7,90.1,2025-06-06,6.0
4959,user_00373,Tablet,Action,First Quest,37.2,88.2,2025-06-15,6.0
6821,user_09581,Tablet,Action,Quest Hero,42.6,43.2,2024-03-11,3.0
8034,user_01901,Laptop,Action,Storm Family,35.0,72.0,2025-01-27,1.0
9435,user_,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df['watch_duration_seconds'] = df['watch_duration_minutes'].map(lambda x : x * 60 )
df['watch_duration_seconds']

0       3834.0
1       3024.0
2       2082.0
3       3594.0
4       1860.0
         ...
9431    1380.0
9432    3378.0
9433    4806.0
9434    5802.0
9435       NaN
Name: watch_duration_seconds, Length: 9436, dtype: float64